### ISSUE TITLE
Request for Bot for SanskritOCR output

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/sanskrit-ocr-r0#7]
@vvasuki 
I have posted the output generated via SanskritOCR for gaNaratnamahodadhi [here](https://github.com/sanskrit-coders/sanskrit-ocr-r0/tree/master/vaak/vyAkaraNam/ganaratnamahodadhi/SanskritOCR).
SanskritOCR has an option to give output pagewise.
e.g.
This PDF file had 330 pages.
The output .txt are named 0000.txt to 0329.txt.

I have very limited knowledge about java or bots in general. Would you be kind enough to device a bot for uploading these filew in index pages 1 to 330.
Once you have developed this kind of bot, I would be able to upload scans of SanskritOCR at a faster pace.

**Comment by vvasuki** [comment]
Mostly done with [this](https://github.com/sanskrit-coders/sanskritnlpjava/commit/4deded27ecf89ceb4207b305d70211d2f0ebef95#diff-40daa01b4b1988fd90a3ea6f91d4bebd). Havent yet made it so that you can run it by yourself, but your pages are being uploaded at the rate of 1 per minute (bot flag not approved, so its slow).

**Comment by drdhaval2785** [comment]
I could see the content. Speed is not an issue as of now. But please make some readme kind of thing to enable me to run it too. It works well.
